version: "3.8"

services:
  app:
    build: .
    container_name: chatbotutec-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
